GH- 2543 - Update release workflows.

diff --git a/.github/workflows/release-train-ready.yml b/.github/workflows/release-train-ready.yml
--- a/.github/workflows/release-train-ready.yml
+++ b/.github/workflows/release-train-ready.yml
@@ -4,11 +4,12 @@ run-name: "${{ inputs.release-train }} – Ready"
   workflow_dispatch:
     inputs:
       release-train:
-        description: "Name of the release train"
+        description: "Release train"
         required: true
         type: "string"
       release-train-repository:
-        description: "Repository that is orchestrating the release train"
+        default: "spring-io/release-train"
+        description: "Release train repository"
         required: true
         type: "string"
 permissions:
@@ -21,5 +22,16 @@ jobs:
     - name: "Ready"
       id: "ready"
       env:
-        GH_TOKEN: "${{ secrets.ACTIONS_RELEASE_TOKEN }}"
-      run: "gh workflow run ready --repo ${{ inputs.release-train-repository }} --ref ${{ inputs.release-train }} --field release-branch=${{ github.ref_name }} --field release-repository=${{ github.repository }}"
+        GH_TOKEN: "${{ secrets.RELEASE_TRAIN_PARTICIPANT_GITHUB_TOKEN }}"
+      run: |-
+        run_url=$(gh workflow run ready --repo ${{ inputs.release-train-repository }} --ref ${{ inputs.release-train }} --field release-branch=${{ github.ref_name }} --field release-repository=${{ github.repository }})
+        echo "Dispatched workflow run. Waiting for $run_url to complete."
+        run_id=${run_url##*/}
+        watch_exit_code=0
+        gh run watch $run_id --repo ${{ inputs.release-train-repository }} --exit-status --interval=3 > /dev/null 2>&1 || watch_exit_code=$?
+        if [[ $watch_exit_code -eq 0 ]]; then
+          echo "Workflow run succeeded."
+        else
+          echo "Workflow run failed."
+        fi
+        exit $watch_exit_code
